// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFWebAPI.Data.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateOnly Fecha { get; set; }

    public int IdFormaPago { get; set; }

    public int IdCliente { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormaPago IdFormaPagoNavigation { get; set; }
}