// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFWebAPI.Data.Models;

public partial class FormaPago
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}